export const GET_SERVICES_SUCCSESS="GET_SERVICES_SUCCSESS"
export const GET_SERVICES_REQUEST="GET_SERVICES_REQUEST"
export const GET_SERVICES_ERROR="GET_SERVICES_ERROR"

export const DELETE_SERVICES_SUCCSESS="DELETE_SERVICES_SUCCSESS"
export const DELETE_SERVICES_REQUEST="DELETE_SERVICES_REQUEST"
export const DELETE_SERVICES_ERROR="DELETE_SERVICES_ERROR"