export const GET_IMAGE_SUCCSESS="GET_IMAGE_SUCCSESS"
export const GET_IMAGE_REQUEST="GET_IMAGE_REQUEST"
export const GET_IMAGE_ERROR="GET_IMAGE_ERROR"




export const POST_IMAGE_SUCCSESS="POST_IMAGE_SUCCSESS"
export const POST_IMAGE_REQUEST="POST_IMAGE_REQUEST"
export const POST_IMAGE_ERROR="POST_IMAGE_ERROR"

export const DELETE_IMAGE_SUCCSESS="DELETE_IMAGE_SUCCSESS"
export const DELETE_IMAGE_REQUEST="DELETE_IMAGE_REQUEST"
export const DELETE_IMAGE_ERROR="DELETE_IMAGE_ERROR"

export const UPDATE_IMAGE_SUCCSESS="UPDATE_IMAGE_SUCCSESS"
export const UPDATE_IMAGE_REQUEST="UPDATE_IMAGE_REQUEST"
export const UPDATE_IMAGE_ERROR="UPDATE_IMAGE_ERROR"